### ISSUE TITLE
Crash on Swearing

### ISSUE THREAD

**Issue by DI3HARD139** [Tmanyo/server_helper#3]
Ok so in the beginning I though it was something I screwed up on my fork but apparently present in the original mod. 
`init.lua:193: attempt to perform arithmetic on local 'a' (a nil value)` Line 193

The language_control portion isn't able to address
`minetest.register_on_joinplayer(function(player)
    local name = player:get_player_name()
   server_helper.players[name] = {shout = 0,}
   server_helper.players[name] = {location = 0,}
end)` at lines 46-50

**Comment by DI3HARD139** [comment]
Potential working fix:

`minetest.register_on_joinplayer(function(player)`
`local name = player:get_player_name()`
`server_helper.players[name] = {shout = 0,}`
`end)`

`minetest.register_on_chat_message(function(name, message)`
`if minetest.setting_getbool("language_control") == true then`
`if string.match(message, "word") or string.match(message, "word") or string.match(message, "word") or`
`string.match(message, "word") or string.match(message, "word") or string.match(message, "word") or`
`string.match(message, "word") or string.match(message, "word") or string.match(message, "word") or`
`string.match(message, "word") or string.match(message, "word") or string.match(message, "wrod") or`
`string.match(message, "word") or string.match(message, "word") or string.match(message, "word") or`
`string.match(message, "word") then`
`local d = server_helper.players[name].shout`
`d = d + 1`
`server_helper.players[name] = {shout = d,}`
`if d < 5 then`
`minetest.chat_send_all("<The All Seeing Eye> Please do not use foul language.")`
`elseif d >= 5 then`
`minetest.kick_player(name, "You didn't stop using foul language!")`
`minetest.chat_send_all(name .. " was just kicked for not following the rules.")`
`end`
`end`
`end`
`end)`

**Comment by Tmanyo** [comment]
We never had this issue.  Are you sure you didn't delete a line needed in the fork?

**Comment by DI3HARD139** [comment]
Nope. I just did a fresh pull from github, copied it to the mods folder and there it is.

**Comment by Tmanyo** [comment]
Did you test it in single player or multiplayer?  I tested it in single player and it works just fine.  Did you use 1.1 release or did you download right from the clone or download drop down?

**Comment by DI3HARD139** [comment]
Download drop down

**Comment by NathanSalapat** [comment]
Inadvertently fixed this bug by fixing a problem with caps usage. (Bad table setup in the on_join function.)
