### ISSUE TITLE
Spam caused by keyword "no"

### ISSUE THREAD

**Issue by SmallJoker** [Tmanyo/server_helper#4]
The chat message "no" causes a flood of "Ok." messages.

**Comment by Tmanyo** [comment]
Can you please provide more detail?  I have tried in singleplayer.  No does not do anything on its own.  There may be a bug with some conversational code.  So say "The All Seeing Eye" asks you a question and you respond no, is that when it floods or maybe the question was never answered until someone said no?

**Comment by SmallJoker** [comment]
Closing till able to reproduce and take a screenie of the chat history.
